Repository trayl-app/monviso, pull requests merged in 2022-10, with the labels that each got.

#5 Added creation user function #(4-create-user-function)
  package.json
  src/users/dto/create-user.dto.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
  yarn.lock
Labels: enhancement, feature

#8 refactor and code cleanup (#7)
  package.json
  prisma/client.ts
  prisma/migrations/20221011055642_initial_user/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/seed.ts
  src/app.module.ts
  src/common/configs/config.ts
  src/config/database.ts
  src/main.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.spec.ts
  src/prisma/prisma.service.ts
  src/repository.ts
  src/users/fixtures/user.entity.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.spec.ts
  src/users/users.repository.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  tsconfig.build.json
  tsconfig.json
Labels: debt, maintenance

#13 manage entities/dtos
  package.json
  src/main.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/fixtures/user.entity.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  yarn.lock
Labels: enhancement, maintenance

#16 add and setup swagger (#15)
  package.json
  src/main.ts
  src/users/dto/create-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  yarn.lock
Labels: enhancement, feature

#31 handle authorization middleware in development
  src/app.module.ts
  src/auth/auth.middleware.ts
  src/me/me.controller.ts
Labels: effort: low 🏝, priority: low 🚛, type: maintenance 👨🏻‍🔧
